# Generated by Django 4.0 on 2024-06-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0005_alter_group_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='recurring',
            field=models.BooleanField(default=False),
        ),
    ]
